In [1]:
import numpy as np

In [13]:
arr = np.array([23, 45, 67, 89,45, 10])

In [14]:
print(arr)

[23 45 67 89 45 10]


In [15]:
arr

array([23, 45, 67, 89, 45, 10])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr[2]

np.int64(67)

In [18]:
arr[3] = 40

In [19]:
arr

array([23, 45, 67, 40, 45, 10])

In [9]:
arr[2] = 40 

In [10]:
arr

array([23, 45, 40, 40, 10])

In [22]:
arr = np.array([23, 45, 67, 89.45, 45, True, "pune", 10])

In [23]:
arr

array(['23', '45', '67', '89.45', '45', 'True', 'pune', '10'],
      dtype='<U32')

In [24]:
arr.dtype

dtype('<U32')

In [26]:
arr 

array(['23', '45', '67', '89.45', '45', 'True', 'pune', '10'],
      dtype='<U32')

In [89]:
arr *2

array([[ 2,  4,  6],
       [ 8,  4, 10],
       [12, 18,  8],
       [12,  6, 18]])

Check whch one is faster......array/list

In [28]:
import time

In [30]:
time.time()

1750657539.3338916

In [31]:
s = 100000

list1 = list(range(s))

arr1 = np.array(list1)

In [33]:
#for list

start_time = time.time()
x = [i * 2 for i in list1]
time_list = time.time() - start_time
print("time taken by list:", time_list)

time taken by list: 0.015856504440307617


In [36]:
#for array

start_time = time.time()
y = arr1 * 2
time_arr = time.time() - start_time
print("time taken by array:", time_arr)

time taken by array: 0.0026357173919677734


In [37]:
time_list / time_arr

13.725463591135233

####arange

In [38]:
a = np.arange(11)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
arr.ndim

1

2-D arrays

In [46]:
arr = np.array([[1,2,3],[4,2,5],[6,9,4],[6,3,9]])

In [47]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 9]])

In [48]:
arr.size

12

In [49]:
arr.shape

(4, 3)

In [50]:
arr.flatten()

array([1, 2, 3, 4, 2, 5, 6, 9, 4, 6, 3, 9])

In [51]:
arr.flatten().ndim

1

In [52]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 9]])

In [53]:
arr.reshape(6, 2)

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 9],
       [4, 6],
       [3, 9]])

In [54]:
arr.reshape(2, 6)


array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 9]])

In [55]:
arr.reshape(2, -1)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 9]])

In [58]:
help()

Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".



help>  how to change dimenison of array


No Python documentation found for 'how to change dimenison of array'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



help>  dimension


No Python documentation found for 'dimension'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



help>  hi


No Python documentation found for 'hi'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



help>  quit



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [61]:
arr.reshape(3, 2 ,2)

array([[[1, 2],
        [3, 4]],

       [[2, 5],
        [6, 9]],

       [[4, 6],
        [3, 9]]])

In [63]:
arr.ndim

2

slicing

In [64]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 9]])

In [65]:
arr1 = np.arange(3, 13)
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
arr[3:7]

array([[6, 3, 9]])

In [67]:
arr[1:3, 0:2]

array([[4, 2],
       [6, 9]])

In [72]:
arr[1:3, 0:3]

array([[4, 2, 5],
       [6, 9, 4]])

In [73]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
np.mean(arr1)

np.float64(7.5)

In [75]:
np.std(arr1)

np.float64(2.8722813232690143)

#### linear Algebra

In [78]:
a = np.array([[1,4], [4,9]])
b = np.array([[3,3], [10,1]])


In [79]:
a

array([[1, 4],
       [4, 9]])

In [80]:
b

array([[ 3,  3],
       [10,  1]])

In [81]:
np.dot(a,b)

array([[ 43,   7],
       [102,  21]])

In [83]:
np.linalg.det(a)

np.float64(-6.999999999999999)

In [84]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [85]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

In [87]:
# vector

vec = np.array([3, 6])

In [88]:
np.linalg.norm(vec)

np.float64(6.708203932499369)

# Practice questions

#create a numpy array of shape (3,3) wth values ranging from 1 t0 9

In [93]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


02_Given a 1D numpy array [10, 20, 30, 40, 50] write code to reverse the array

In [96]:
arr = np.array([10, 20, 30, 40, 50])
reversed_arr = arr[::-1]
print(reversed_arr)

[50 40 30 20 10]


03_create a 5x5 numpy array filled with zeros and set the value of the middle element to 1

In [97]:
arr = np.zeros((5, 5))  
arr[2, 2] = 1 
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


04_generate a numpy array with 20 random integers between 1 and 100. replace all even numbers with -1

In [99]:
arr = np.random.randint(1, 101, size=20)  
arr[arr % 2 == 0] = -1  
print(arr)

[-1 -1 -1  3 -1 11 45 -1 -1 29 37 -1 39 89 97 61 47 53 43 -1]


05_Given a numpy array a = np.array([[1, 2], [3, 4], [5, 6]]), extract the second column

In [108]:
a = np.array([[1, 2], [3, 4], [5, 6]])
ex_arr = a[:, 1]
print(a)
print("-----------")
print(ex_arr)

[[1 2]
 [3 4]
 [5 6]]
-----------
[2 4 6]


#06_Create a NumPy array and convert to 2x2 matrix



In [2]:
import numpy as np

In [3]:

arr = np.array([1, 2, 3, 4])
matrix = arr.reshape(2, 2)
print("2x2 Matrix:\n", matrix)


2x2 Matrix:
 [[1 2]
 [3 4]]


07_Element-wise operations on two 2x2 arrays

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:\n", add)
print("---------------------")
print("Subtraction:\n", sub)
print("---------------------")
print("Multiplication:\n", mul)
print("---------------------")
print("Division:\n", div)


Addition:
 [[ 6  8]
 [10 12]]
---------------------
Subtraction:
 [[-4 -4]
 [-4 -4]]
---------------------
Multiplication:
 [[ 5 12]
 [21 32]]
---------------------
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


08_10 linearly spaced values between 0 and 1


In [6]:
linear_values = np.linspace(0, 1, 10)
print("Linearly spaced values:\n", linear_values)


Linearly spaced values:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


09_Compute mean, median, and standard deviation

In [9]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>
)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For in

In [10]:
help(np.median)

Help on _ArrayFunctionDispatcher in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.

    Returns the median of the array elements.

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default,
        axis=None, will compute the median along a flattened version of
        the array. If a sequence of axes, the array is first flattened
        along the given axes, then the median is computed along the
        resulting flattened axis.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use 

In [7]:
data = np.array([10, 20, 30, 40, 50])

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


10_Normalize each column of a 2D array

In [8]:
def normalize_col(arr):
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0)
    std[std == 0] = 1
    return (arr - mean) / std

data = np.array([[1, 2], [3, 4], [5, 6]])
normalized = normalize_col(data)
print("Normalized array:\n", normalized)


Normalized array:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
